# Generated by Django 5.2.7 on 2025-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_popular_statuspedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'Envio', 'verbose_name_plural': 'Envios'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='statuspedido',
            options={'ordering': ['ordem'], 'verbose_name': 'Status do Pedido', 'verbose_name_plural': 'Status dos Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='transportadora',
            options={'verbose_name': 'Transportadora', 'verbose_name_plural': 'Transportadoras'},
        ),
        migrations.AddField(
            model_name='envio',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='data_postagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cpf_destinatario',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ do destinatário (obrigatório para envio)', max_length=14),
        ),
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Altura em cm', max_digits=8),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Comprimento em cm', max_digits=8),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Largura em cm', max_digits=8),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0.1, help_text='Peso em kg (ex: 0.500 para 500g)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='envio',
            name='eventos_rastreio',
            field=models.JSONField(default=list, help_text='Histórico completo de eventos de rastreamento da transportadora'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['codigo_rastreio'], name='core_envio_codigo__ea90e5_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['status_entrega'], name='core_envio_status__de6549_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['data_postagem'], name='core_envio_data_po_1b3c57_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'status'], name='core_produt_categor_e629e2_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['data_criacao'], name='core_produt_data_cr_d93a5a_idx'),
        ),
    ]
