# Generated by Django 5.2.7 on 2025-11-25 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_managers_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem das imagens (0 = primeira)', verbose_name='Ordem de Exibição')),
                ('legenda', models.CharField(blank=True, help_text='Legenda opcional para a imagem', max_length=200, verbose_name='Legenda')),
                ('is_principal', models.BooleanField(default=False, help_text='Marcar como imagem principal do produto', verbose_name='Imagem Principal')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['ordem', 'data_criacao'],
                'indexes': [models.Index(fields=['produto', 'ordem'], name='core_imagem_produto_fe7f4d_idx'), models.Index(fields=['produto', 'is_principal'], name='core_imagem_produto_9941fc_idx')],
            },
        ),
    ]
