# Generated by Django 5.2.7 on 2025-12-04 18:29

import core.models.avaliacoes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_imagemproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_geral', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nota_qualidade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nota_entrega', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nota_custo_beneficio', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titulo', models.CharField(help_text='Título da sua avaliação', max_length=200)),
                ('comentario', models.TextField(help_text='Conte sua experiência detalhada')),
                ('tempo_de_uso', models.CharField(blank=True, max_length=50, null=True)),
                ('melhor_ponto', models.CharField(blank=True, max_length=200, null=True)),
                ('pior_ponto', models.CharField(blank=True, max_length=200, null=True)),
                ('recomendaria', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Moderação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('spam', 'Marcado como Spam'), ('oculto', 'Oculto por Moderação')], default='pendente', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(db_index=True, default=0)),
                ('dislikes', models.PositiveIntegerField(db_index=True, default=0)),
                ('util', models.PositiveIntegerField(db_index=True, default=0)),
                ('nao_util', models.PositiveIntegerField(db_index=True, default=0)),
                ('compartilhamentos', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('hash_avaliacao', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('moderador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_moderadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='core.avaliacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_util', to='core.avaliacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('spam', 'Conteúdo promocional/Spam'), ('inadequado', 'Conteúdo inadequado ou ofensivo'), ('falso', 'Informação falsa ou enganosa'), ('copyright', 'Violação de direitos autorais'), ('privacidade', 'Violação de privacidade'), ('outro', 'Outro motivo')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='denuncias/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analisado', 'Analisado'), ('descartado', 'Descartado')], db_index=True, default='pendente', max_length=20)),
                ('resolucao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='core.avaliacao')),
                ('moderador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_analisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MidiaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.avaliacoes.upload_to_avaliacao)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.avaliacoes.upload_to_avaliacao)),
                ('legenda', models.CharField(blank=True, max_length=200, null=True)),
                ('duracao_video', models.DurationField(blank=True, null=True)),
                ('resolucao', models.CharField(blank=True, max_length=20, null=True)),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('hash_arquivo', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('mimetype', models.CharField(blank=True, max_length=100, null=True)),
                ('aprovado', models.BooleanField(db_index=True, default=False)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('scan_virus', models.BooleanField(default=False)),
                ('scan_conteudo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='core.avaliacao')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['produto', 'status', 'created_at'], name='core_avalia_produto_7c8311_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['produto', 'nota_geral'], name='core_avalia_produto_98bc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['status', 'publicado_em'], name='core_avalia_status_3146d3_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['usuario', 'created_at'], name='core_avalia_usuario_cbb82e_idx'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('produto', 'usuario'), name='unique_avaliacao_produto_usuario'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(condition=models.Q(('hash_avaliacao__isnull', False)), fields=('hash_avaliacao',), name='unique_hash_avaliacao'),
        ),
        migrations.AddIndex(
            model_name='avaliacaolike',
            index=models.Index(fields=['avaliacao', 'tipo'], name='core_avalia_avaliac_0e3c48_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaolike',
            index=models.Index(fields=['usuario', 'created_at'], name='core_avalia_usuario_8ee6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaolike',
            index=models.Index(fields=['ip_address', 'created_at'], name='core_avalia_ip_addr_588c67_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaolike',
            index=models.Index(fields=['fingerprint', 'created_at'], name='core_avalia_fingerp_05d3c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaolike',
            unique_together={('avaliacao', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='avaliacaoutil',
            index=models.Index(fields=['avaliacao', 'util'], name='core_avalia_avaliac_d9698c_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaoutil',
            index=models.Index(fields=['usuario', 'created_at'], name='core_avalia_usuario_b4456d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoutil',
            unique_together={('avaliacao', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='denunciaavaliacao',
            index=models.Index(fields=['avaliacao', 'status'], name='core_denunc_avaliac_2477fc_idx'),
        ),
        migrations.AddIndex(
            model_name='denunciaavaliacao',
            index=models.Index(fields=['status', 'created_at'], name='core_denunc_status_2249ab_idx'),
        ),
        migrations.AddIndex(
            model_name='denunciaavaliacao',
            index=models.Index(fields=['motivo', 'status'], name='core_denunc_motivo_fe0ade_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='denunciaavaliacao',
            unique_together={('avaliacao', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='midiaavaliacao',
            index=models.Index(fields=['avaliacao', 'aprovado'], name='core_midiaa_avaliac_943057_idx'),
        ),
        migrations.AddIndex(
            model_name='midiaavaliacao',
            index=models.Index(fields=['hash_arquivo'], name='core_midiaa_hash_ar_6e48d9_idx'),
        ),
        migrations.AddIndex(
            model_name='midiaavaliacao',
            index=models.Index(fields=['tipo', 'aprovado'], name='core_midiaa_tipo_77e91f_idx'),
        ),
    ]
