# Generated by Django 5.2.7 on 2025-12-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_avaliacao_avaliacaolike_avaliacaoutil_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='unique_avaliacao_produto_usuario',
        ),
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='unique_hash_avaliacao',
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaolike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoutil',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='denunciaavaliacao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='hash_avaliacao',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Moderação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('spam', 'Marcado como Spam'), ('oculto', 'Oculto por Moderação')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='midiaavaliacao',
            name='hash_arquivo',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['produto', 'usuario'], name='idx_unique_prod_user'),
        ),
        migrations.AddIndex(
            model_name='avaliacaolike',
            index=models.Index(fields=['avaliacao', 'usuario'], name='idx_unique_like'),
        ),
        migrations.AddIndex(
            model_name='avaliacaoutil',
            index=models.Index(fields=['avaliacao', 'usuario'], name='idx_unique_util'),
        ),
        migrations.AddIndex(
            model_name='denunciaavaliacao',
            index=models.Index(fields=['avaliacao', 'usuario'], name='idx_unique_denuncia'),
        ),
    ]
